### ISSUE TITLE
DPL-879 [BUG] Fix configuration hierarchy mismapping

### ISSUE THREAD

**Issue by StephenHulme** [sanger/traction-service#1091]
**Describe the bug**
Fix configuration hierarchy mismapping in the YAML config files used in message and sample-sheet generation.

**RT Ticket Number**
N/A

**To Reproduce**
Steps to reproduce the behaviour:
1. Create config:
    ```yml
    top:
      middle:
        bottom: 'leaf'
    ```
2. Access `top.bottom`

**Expected behaviour**
Returns error

**Actual behaviour**
Returns `leaf`

**Additional context**
Blocker for #1058
